frcho_crontask_homepage:
    path:     /
    defaults: { _controller: FrchoCrontaskBundle:Default:index }
frcho_cron_task:
    path:     /viewTask
    defaults: { _controller: "FrchoCrontaskBundle:CronTask:cronTask" }
frcho_cron_task_update:
    path:     /cronTaskUpdate
    defaults: { _controller: "FrchoCrontaskBundle:CronTask:cronTaskUpdate" }    
