frcho_cron_task:
    path:     /viewTask
    defaults: { _controller: Frcho\Bundle\CrontaskBundle\Controller\CronTaskController::cronTaskAction }
frcho_cron_task_update:
    path:     /cronTaskUpdate
    defaults: { _controller: Frcho\Bundle\CrontaskBundle\Controller\CronTaskController::cronTaskUpdateAction }    
