parameters:
    command.default_name: Javier
    
services:
    frcho.crontask_default:
        class: Frcho\Bundle\CrontaskBundle\Util\DefaultCommands
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
            
    frcho..form.type.cron_task:
        class: Frcho\Bundle\CrontaskBundle\Form\CronTaskType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }
