parameters:
    frcho.crontask_command:  Frcho\Bundle\CrontaskBundle\Util\DefaultCommands
    
services:
    frcho.crontask_default:
        class: '%frcho.crontask_command%'
        arguments: [ "@doctrine.orm.entity_manager","@service_container" ]
        public: true
            
    Frcho\Bundle\CrontaskBundle\Command\CronTasksRunCommand:
        tags:
            - { name: 'console.command', command: 'crontasks:run' }   

    frcho..form.type.cron_task:
        class: Frcho\Bundle\CrontaskBundle\Form\CronTaskType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }